#!/usr/bin/env bash
set -e

source /home/kochiku/.bashrc

set -x

function ensure_phantomjs() {
  local phantom_version=$(cat .phantom-version)
  if ! phantomenv versions | grep -v $phantom_version > /dev/null; then
    phantomenv install $phantom_version
  fi
}

function ensure_nodejs() {
  nodenv install --skip-existing $(cat .node-version)
}

function install_dependencies() {
  ensure_phantomjs
  ensure_nodejs
  echo "Node Version: $(node -v)"
  echo "Yarn Version: $(yarn --version)"
  echo "NPM Version: $(npm -v)"
  echo "Phantom Version: $(phantomjs -v)"
  yarn install
  bower install
}

function prepare_and_run() {
  install_dependencies
  ember test --reporter dot
}

prepare_and_run
success=$?
exit $success
